source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '15.0'

target 'ABCenterConfig_Example' do
  pod 'ABCenterConfig', :path => '../'

  target 'ABCenterConfig_Tests' do
    inherit! :search_paths

    
  end
end
